### ISSUE TITLE
Issue with Splunk not getting logs with Line Feed in the event - Post 1.4.4

### ISSUE THREAD

**Issue by skirven4** [splunk/splunk-connect-for-kubernetes#597]
**What happened**: We upgraded from SCK 1.4.1, where this issue was not occurring, to SCK 1.4.7, where it is. What we are observing is where Multi-Line events that contain a single blank line appear to get dropped from Splunk completely. 
 
**What you expected to happen**: The SCK needs to concat the lines, in addition to leaving the blank line intact.
 
**How to reproduce it (as minimally and precisely as possible)**: Create a multi-line log message and place a single blank line between them, and you should observe the line not get ingested. I had my flushInterval at 1, and did change it to 5, and that didn’t help. Rolling back to 1.4.1 with exactly the same values made Splunk start ingesting them again.
 
**Anything else we need to know?**:
 
**Environment**:
- Kubernetes version (use `kubectl version`): 1.19.3
- Ruby version (use `ruby --version`):
- OS (e.g: `cat /etc/os-release`): Centos 7
- Splunk version: 7.3.8
- Splunk Connect for Kubernetes helm chart version: 1.4.7
- Others:

**Comment by vinzent** [comment]
Maybe related to https://github.com/splunk/fluent-plugin-splunk-hec/commit/f003c571720b5c29b4ca0631e727e38a18decfee

**Comment by skirven4** [comment]
@vinzent  - This is a good find. Thanks. And to the comments, I wonder if the drop is being done before the ML concat, which may break the event, causing it to drop?

**Comment by vinzent** [comment]
if its the fluent-plugin-spunk-hec change you should see `Event after formatting was blank, not sending` in the logs.

anyway might help if you share your helm values (don't forget to exclude any credentials).

also there were obviously more releases between 1.4.1 and 1.4.7. knowing the exact version where it breaks might help alot.

**Comment by vinzent** [comment]
it's probably PR #485 (commit 3e93231eabd83638025378d9338fc3621a569dca) 

https://github.com/splunk/splunk-connect-for-kubernetes/blob/604700eb8f72d90b5e4a573621519309e5f7c34a/helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-logging/templates/configMap.yaml#L240-L247

**Comment by skirven4** [comment]
It could be. I'm going to see about getting the helm chart, and also setting up a Jenkins Deployment such that we can specify the release number, so we can walk each version through. 

I'll update when I know more.

**Comment by skirven4** [comment]
I have confirmed that this behavior does not exist with version 1.4.3, and does with 1.4.4, so it was introduced in 1.4.4

**Comment by matthewmodestino** [comment]
blanks have been tough cause they cause dropped hec posts if they make it to the hec endpoint. you are right that as long as concat is correct you wont have the issue...must be a check to remove empty lines...

**Comment by hanswurscht** [comment]
Hi,

we are also hitting this bug.
Maybe setting the pattern in the grep filter to

    \A\z

can fix this?

- Lorenz

**Comment by pc-mreeves** [comment]
Hi all! 

Was this fixed in https://github.com/splunk/splunk-connect-for-kubernetes/releases/tag/1.4.8?
![image](https://user-images.githubusercontent.com/22081352/133306570-8e851c29-cac8-4922-bc6b-dee9201676b0.png)

**Comment by skirven4** [comment]
Unfortunately, no. I did test that and it’s still broken.Stephen


Sent from Yahoo Mail for iPhone


On Tuesday, September 14, 2021, 1:37 PM, Michael Reeves ***@***.***> wrote:




Hi all!

Was this fixed in https://github.com/splunk/splunk-connect-for-kubernetes/releases/tag/1.4.8?


—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by rockb1017** [comment]
I released 1.4.10 where we changed the regex.
if that doesn't fix it, we also added an option to disable it.
you can set `containers.removeBlankEvents` to false.

Let us know if there is issues. Thanks!
